Revert "Add SQLite plugin (#6643)" (#6670)
This reverts commit 30e5c77f4cb7ff61df0a56a117ba3399836e890f.

What changed?

#6643

Why?

Internally we use a lower version of indirect dependency. tetratelabs/wazero@v1.1.0...v1.8.2
And this indirect dependency is actually used by an incident mitigation tooling. So it's safer to keep the lower version.

However, using the lower version doesn't build because of go-sqlite3 library we used

% make build                                         
Building all packages and submodules...
# github.com/ncruces/go-sqlite3/internal/alloc
../../../go/pkg/mod/github.com/ncruces/go-sqlite3@v0.22.0/internal/alloc/alloc_unix.go:12:44: undefined: experimental.LinearMemory
make: *** [build] Error 1

How did you test it?

unit test